name: Auto Deploy to Netlify

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  auto-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js for both frontend and backend
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies in the "public" (frontend) folder
      - name: Install dependencies for frontend
        run: npm install
        working-directory: ./public

      # Step 4: Install dependencies in the "server" (backend) folder
      - name: Install dependencies for backend
        run: npm install
        working-directory: ./server

      # Step 4.5: Grant execute permissions to mocha in the "server" folder
      - name: Grant execute permissions to mocha
        run: chmod +x ./node_modules/.bin/mocha
        working-directory: ./server

      # Step 5: Run tests for the frontend (if you have tests set up in Jest)
      - name: Run tests for frontend
        run: npm test
        working-directory: ./public

      # Step 7: Build the frontend (public) project
      - name: Build the frontend project
        run: npm run build
        working-directory: ./public

      # Step 8: Deploy to Netlify
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --build --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
